<form action="<?= route('problems.update', ['id' => $problem->id]) ?>" method="POST" class="<?= $problem->hasErrors() ? '' : 'was-validated' ?>" novalidate>
    <input type="hidden" name="_method" value="PUT">
    <div class="mb-3">
        <label for="problem_title" class="form-label">Título:</label>
        <input type="text" name="problem[title]" class="form-control" id="problem_title" value="<?= $problem->title ?>" required>
        <div class="invalid-feedback"><?= $problem->errors('title') ? $problem->errors('title') : '' ?></div>
    </div>

    <button type="submit" class="btn btn-primary">Atualizar</button>
</form>