<div class="row">
    <div class="col-8 mb-3">
        <div class="input-group">
            <input type="text" class="form-control" placeholder="Procurar problemas" aria-label="Recipient's username" aria-describedby="button-addon2">
            <button class="btn btn-outline-primary" type="button">
                Pesquisar...
            </button>
        </div>
    </div>
    <div class="col-4">
        <a href="/pages/problems/new.php" class="btn btn-outline-primary">
            <i class="fe fe-plus"></i>
            Registrar Problema
        </a>
    </div>
</div>

<table class="table">
    <thead>
        <th>ID</th>
        <th>Título</th>
    </thead>
    <tbody>
        <?php foreach ($problems as $index => $problem) : ?>
            <tr>
                <td><a href="/pages/problems/show.php?id=<?= $index ?>">#<?= $index ?></a></td>
                <td><?= $problem ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>