<nav aria-label="Page navigation">
    <ul class="pagination justify-content-end">

        <?php if ($paginator->hasPreviousPage()) : ?>
            <li class="page-item">
                <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $paginator->previousPage()]) ?>">Anterior</a>
            </li>
        <?php else : ?>
            <li class="page-item disabled">
                <a class="page-link">Anterior</a>
            </li>
        <?php endif; ?>

        <?php for ($page = 1; $page <= $paginator->totalOfPages(); $page++) : ?>
            <li class="page-item <?= $paginator->isPage($page) ? 'active' : '' ?>">
                <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $page]) ?>"><?= $page ?></a>
            </li>
        <?php endfor; ?>

        <?php if ($paginator->hasNextPage()) : ?>
            <li class="page-item">
                <a class="page-link" href="<?= route($paginator->getRouteName(), ['page' => $paginator->nextPage()]) ?>">Próxima</a>
            </li>
        <?php else : ?>
            <li class="page-item disabled">
                <a class="page-link">Próxima</a>
            </li>
        <?php endif; ?>
    </ul>
</nav>

<div class="d-flex justify-content-end"><?= $paginator->entriesInfo() ?></div>