<div class="d-flex">
    <div>
        <img id="image_preview" class="avatar rounded img-thumbnail" src="<?= $this->current_user->avatar()->path() ?>" alt="avatar">

        <form action="<?= route('profile.avatar') ?>" method="POST" enctype="multipart/form-data">
            <input id="image_preview_input" type="file" name="user_avatar" id="user_avatar">
            <div class="d-grid mt-2">
                <button id="image_preview_submit" type="submit" class="btn btn-fill btn-primary">Atualizar</button>
            </div>
        </form>

    </div>
    <div class="mx-5">
        <div class="rounded">
            <h3><?= $this->current_user->name ?></h3>
            <span class="text-primary">Estudante de Sistema para Internet</span>
        </div>
        <ul class="list-unstyled mt-2">
            <li>
                <span>Email: <?= $this->current_user->email ?></span>
            </li>
        </ul>
    </div>
</div>